#!/bin/sh

#
# This file is part of OCaml-Java compiler.
# Copyright (C) 2007-2014 Xavier Clerc.
# Original file (stdlib/Compflags in the OCaml source
# distribution) is Copyright (C) INRIA.
#
# OCaml-Java compiler is free software; you can redistribute it and/or modify
# it under the terms of the Q Public License v1.0 as published by
# Trolltech (with a change to choice of law).
#
# OCaml-Java compiler is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# Q Public License for more details.
#
# You should have received a copy of the Q Public License
# along with this program.  If not, see
# <http://opensource.org/licenses/QPL-1.0>.
#

case $1 in
  pervasives.cm[ij]) echo ' -nopervasives';;
  camlinternalOO.cmi) echo ' -nopervasives';;
  camlinternalOO.cmj) echo ' -inline 0';;
  buffer.cmj) echo ' -inline 3';;
  buffer.cm[ij]|printf.cm[ij]|format.cm[ij]|scanf.cm[ij]) echo ' -w A';;
  scanf.cmj) echo ' -inline 9';;
  arrayLabels.cmj) echo ' -nolabels';;
  listLabels.cmj) echo ' -nolabels';;
  stringLabels.cmj) echo ' -nolabels';;
  moreLabels.cmj) echo ' -nolabels';;
  *) echo ' ';;
esac
